Documentation/configdoc.md, Documentation/modelsdoc.md, Procfile, README.md, config.py, decorators.py, models.py, requirements.txt, serializers.py, views.py
Added authentication for endpoints and improved database handling during requests.
=> Auth, /feed, likes

zimmerman/main/service/comment_service.py, zimmerman/main/service/post_service.py, zimmerman/main/service/reply_service.py, zimmerman/main/service/upload_service.py
Validation updates and error fixes.
=> Updates and fixes

zimmerman/main/controller/user_controller.py, zimmerman/main/service/auth_helper.py, zimmerman/main/service/user_service.py, zimmerman/test/test_user.py
Update routes, controllers and services to get user information by their username.
=> Add: Getting User Info

Makefile, README.md, manage.py, zimmerman/main/__init__.py, zimmerman/main/controller/auth_controller.py, zimmerman/main/controller/comment_controller.py, zimmerman/main/controller/feed_controller.py, zimmerman/main/controller/like_controller.py, zimmerman/main/controller/post_controller.py, zimmerman/main/controller/reply_controller.py, zimmerman/main/controller/upload_controller.py, zimmerman/main/controller/user_controller.py, zimmerman/main/extensions.py, zimmerman/main/model/user.py, zimmerman/main/service/user_service.py
Things that are added are:
* Avatar loader on a service.
* Tips for gunicorn deployment.
* Rate limiting using Flask-Limiter.
* Add image_file columns for Comment and Reply models.
* Removed db.create_all() that may potentially cause issues in deployment.
=> Add features, updates, and code organization.

Procfile, manage.py
Update settings and add basic Procfile for Heroku
=> Add Procfile

requirements.txt, zimmerman/main/config.py, zimmerman/main/controller/user_controller.py, zimmerman/main/model/user.py, zimmerman/main/service/user_service.py, zimmerman/main/util/dto.py, zimmerman/test/test_config.py
* Updated the requirements and removed unnecessary dependencies.
* Updated production config example.
* Added user update api model for validations.
* Adjusted first/last name db models (reduced limits).
* Fixed bio user service.
=> Updated configs, controllers, etc.

zimmerman/main/controller/user_controller.py
Added API Model for Swagger documentation.
=> Removed validate method on update, caused errors.

zimmerman/main/service/auth_helper.py, zimmerman/main/service/comment_service.py, zimmerman/main/service/like_service.py, zimmerman/main/service/post_service.py, zimmerman/main/service/reply_service.py, zimmerman/main/service/upload_service.py, zimmerman/main/service/user_service.py
I have set this to printing the errors instead of sending them to the client as it can contain information about the error in detail to the user.
=> Removed outputting errors.

.gitignore, Procfile, README.md, migrations/README, migrations/alembic.ini, migrations/env.py, migrations/script.py.mako
These fixes issues on Heroku and migrations.
=> Fix db related concerns.

.gitignore, Procfile, migrations/versions/.gitignore
=> Add versions.

zimmerman/main/controller/feed_controller.py, zimmerman/main/service/feed_service.py
* Not returning a posts data in JSON caused the Frontend to repeatedly requests since it did not receive any.
* Added rate limiting on feed routes.
=> Bug fixes and Ratelimiting

README.md
This is definitely not complete could need some more items I will find them as I go along feel free to add more or improve format.
=> Added prerequisites section

zimmerman/auth/service.py, zimmerman/main/controller/post_controller.py, zimmerman/main/service/feed_service.py, zimmerman/main/service/like_service.py, zimmerman/main/service/post_service.py, zimmerman/main/service/reply_service.py, zimmerman/main/service/user_service.py, zimmerman/notification/controller.py, zimmerman/notification/service.py, zimmerman/test/test_config.py
* Fixed like issues (User can like the same posts unlimited amount of times).
* Added current user to post controller.
* Moved get comments/replies method from feed to post service.
* Removed unused imports and imported missing functions.
=> Bug fixes and adjustments.

requirements.txt, zimmerman/main/__init__.py, zimmerman/main/extensions.py
* More info [here](https://github.com/GoogleCloudPlatform/flask-talisman).
* For now it is to force SSL on production run, will utilize more later on for better security.
=> Added Flask-Talisman.

manage.py, zimmerman/main/__init__.py, zimmerman/main/service/feed_service.py, zimmerman/main/service/post_service.py, zimmerman/main/service/user_service.py
* Removed unused imports and linted code.
* Updated the feed service to utilize SQL Joins and Ternary operators for better developer experience  and reduce the amount of queries needed to get posts.
* Update get comments and get replies methods, they will be replaced by "get_initial_(comments/replies)" which will be renamed to those in the future.
* filter_author should replace load_author in the future to reduce DB queries and improve app resource consumption overall.
* Note that this updated doesn't have like checking (yet), so I will not deploy this to Heroku till then.
=> Huge Feed, Post services update.

zimmerman/main/controller/comment_controller.py, zimmerman/main/controller/feed_controller.py, zimmerman/main/extensions.py, zimmerman/main/model/main.py, zimmerman/main/service/comment_service.py, zimmerman/main/service/feed_service.py, zimmerman/main/service/like_service.py, zimmerman/main/service/post_service.py, zimmerman/main/service/reply_service.py, zimmerman/notification/service.py, zimmerman/test/test_comment.py, zimmerman/test/test_comment_model.py, zimmerman/test/test_like.py, zimmerman/test/test_reply_model.py
**This update is mostly like going to break previous versions** but it is going to be better and faster in the long run.
* The whole feed service has been rewritten to query to minimize queries and thus making it more efficient.
* Added limits for feeds.
* Rewritten and refactored the following services: Post, Notification, Comment, Reply. Again, to minimize DB queries, uses less for loops, and reduced the redundancies. 
* Updated the database models.
=> Rewrites, refactoring, and changes.

zimmerman/main/service/feed_service.py, zimmerman/main/service/like_service.py, zimmerman/main/service/post_service.py, zimmerman/notification/service.py, zimmerman/test/test_comment_model.py, zimmerman/test/test_reply_model.py
* Linting
* This fixes the issue on the feed where it would return a sorted array of posts based on their IDs (lowest to highest) which breaks the activity order of id array. Applied the same thing on the notification service as well.
=> Fixed feed issues.

zimmerman/main/service/comment_service.py, zimmerman/main/service/feed_service.py, zimmerman/main/service/post_service.py, zimmerman/main/service/reply_service.py, zimmerman/main/service/user_service.py
* Removed unused imports.
* Removed old load methods.
* Replaced load_author -> filter_author.
=> Deprecate old methods.

Procfile
* Removed `release` Procfile command, it caused unnecessary build failures.
=> Remove release from Procfile.

zimmerman/auth/service.py, zimmerman/main/model/main.py, zimmerman/main/service/comment_service.py, zimmerman/main/service/post_service.py, zimmerman/main/service/user_service.py
* Added Gender / Orientation and validators.
* Usernames are now lowercased.
* Removed reverse methods as they are already ordered by oldest to newest.
=> Adjustments. Orientations *smug*

zimmerman/auth/service.py, zimmerman/auth/util/dto.py
This removes the orientation on registration, it will be an optional in profile editing tab.
This is mostly just for the memes (i.e. identifying as "trap in programming socks")
=> Removed orientation (Will be moved to profile editing).

zimmerman/auth/service.py, zimmerman/util.py
Added utils in which will contain commonly used functions, methods, etc.
=> Added utilities.

zimmerman/auth/service.py, zimmerman/auth/util/dto.py, zimmerman/main/service/comment_service.py, zimmerman/main/service/feed_service.py, zimmerman/main/service/like_service.py, zimmerman/main/service/post_service.py, zimmerman/main/service/reply_service.py, zimmerman/main/service/upload_service.py, zimmerman/main/service/user_service.py, zimmerman/notification/service.py, zimmerman/util.py
Merge Master branch changes cause I'm a doof.
=> Direct commit, woops.

zimmerman/auth/service.py
=> Fix message.

.gitignore, zimmerman/config.py, zimmerman/test/test_config.py, zimmerman/util.py
* Linting and small fix.
* Use SQLite for development instead of PostGreSQL and SQLite + In memory for testing.
=> Use SQLite and adjust code.

zimmerman/api/auth/controller.py, zimmerman/api/main/service/feed/service.py
Documented responses for Swagger UI and added get comments method in feed.
=> Swagger responses and get comments.

zimmerman/api/main/controller/feed_controller.py, zimmerman/api/main/util/dto.py, zimmerman/tests/test_feed.py
* Added mock replies loading route.
* Added comments loading endpoint.
* Fixes and updated api.models.
=> Updated feed controllers and added methods.

zimmerman/api/main/service/comment/utils.py, zimmerman/api/main/service/reply/utils.py, zimmerman/models/content.py
* Fixed bug where it would fail to load replies and causing errors on the server.
* Added lazy-loading for replies and comment relationship.
=> Fixed reply loading issues.

zimmerman/api/main/controller/like_controller.py
* Fixed like controllers had similar class names which caused some weird side effects.
=> Fixed duplicate classes.

Pipfile.lock, manage.py, zimmerman/api/admin/__init__.py, zimmerman/models/likes.py, zimmerman/models/user.py, zimmerman/utils.py
* User's posts, comments, replies properties has been changed to `lazy="dynamic"`.
* Added private property on User model (will be used for later on).
* Added RouteAccessDenied error for users without sufficient permissions on route.
* Linting and removed unused variables.
=> Model updates
